sonarqube:
  build: "sonarqube5.1"
  ports:
   - "9000:9000"
   - "5432:5432"
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://localhost:5432/sonar

db:
  image: postgres
  net: container:sonarqube
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar

jenkins:
  build: "jenkins"
  ports:
   - "8080:8080"